// Auto-generated by MBTG from ITF trace
// Source: examples/counter.itf.json

import { expect } from 'chai';
// TODO: Import your implementation here

describe('Model-Based Test from TLA+ spec', () => {

  it('state 0', () => {
    expect(/* TODO: get counter */).toEqual(0);
    expect(/* TODO: get status */).toEqual("idle");
  });

  it('state 1', () => {
    expect(/* TODO: get counter */).toEqual(1);
    expect(/* TODO: get status */).toEqual("active");
  });

  it('state 2', () => {
    expect(/* TODO: get counter */).toEqual(2);
    expect(/* TODO: get status */).toEqual("active");
  });
});
