{-# LANGUAGE OverloadedStrings #-}

-- | TypeScript test generator.
module MBTG.Generator.TypeScript
  ( generateTypeScript
  , generateStateTest
  , exprToTS
  , generateTypeScriptFile
  ) where

import Data.Map.Strict (Map)
import qualified Data.Map.Strict as Map
import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.Text.IO as TIO
import MBTG.Types (Expr(..), State(..), Trace(..))
import System.Directory (createDirectoryIfMissing)
import System.FilePath (takeBaseName, (</>))

-- | Generate TypeScript test code from ITF trace.
generateTypeScript :: FilePath -> Trace -> Text
generateTypeScript sourceFile trace = T.unlines $
  [ "// Auto-generated by MBTG from ITF trace"
  , "// Source: " <> T.pack sourceFile
  , ""
  , "// Jest test - 'expect' is globally available"
  , "// TODO: Import your implementation here"
  , ""
  , "describe('Model-Based Test from TLA+ spec', () => {"
  ] ++ concatMap (generateStateTest (traceVars trace)) (zip [0..] (traceStates trace))
  ++ ["});"]

-- | Generate test for a single state.
generateStateTest :: [Text] -> (Int, State) -> [Text]
generateStateTest vars (idx, State state) =
  [ ""
  , "  it('state " <> T.pack (show idx) <> "', () => {"
  ] ++ concatMap (generateVarExpectation state) vars ++
  [ "  });"
  ]

-- | Generate expectation for a variable.
generateVarExpectation :: Map Text Expr -> Text -> [Text]
generateVarExpectation state var =
  case Map.lookup var state of
    Nothing -> ["    // WARNING: Variable '" <> var <> "' not found"]
    Just expr -> ["    expect(/* TODO: get " <> var <> " */).toEqual(" <> exprToTS expr <> ");"]

-- | Convert ITF expression to TypeScript literal.
exprToTS :: Expr -> Text
exprToTS = \case
  ExprBool b -> if b then "true" else "false"
  ExprString s -> T.pack (show s)
  ExprBigInt n -> T.pack (show n)
  ExprList es -> "[" <> T.intercalate ", " (map exprToTS es) <> "]"
  ExprTuple es -> "[" <> T.intercalate ", " (map exprToTS es) <> "]"
  ExprSet es -> "new Set([" <> T.intercalate ", " (map exprToTS es) <> "])"
  ExprMap pairs ->
    let items = map (\(k, v) -> exprToTS k <> ": " <> exprToTS v) pairs
    in "{" <> T.intercalate ", " items <> "}"
  ExprRecord fields ->
    let items = map (\(k, v) -> k <> ": " <> exprToTS v) (Map.toList fields)
    in "{" <> T.intercalate ", " items <> "}"
  ExprVariant tag val ->
    "{ tag: " <> T.pack (show tag) <> ", value: " <> exprToTS val <> " }"
  ExprUnserializable s -> "/* " <> s <> " */ null"

-- | Generate TypeScript test file.
generateTypeScriptFile :: FilePath -> FilePath -> Trace -> IO ()
generateTypeScriptFile sourceFile outputPath trace = do
  let code = generateTypeScript sourceFile trace
  TIO.writeFile outputPath code